In [0]:
#Mahnoor Tariq
#IS 427 - IP 2

#imports into program to use np, pd, and sklearn
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.impute import SimpleImputer
#from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_curve, auc

In [3]:
#Import .data file and rename the columns
train = pd.read_csv("ip2ttt_train.data", sep = ",")
train.columns = ["first_row_left", "first_row_middle", "first_row_right", 
                 "center_row_left", "center_row_middle", "center_row_right", 
                 "bottom_row_left", "bottom_row_middle", "bottom_row_right", "is_win"]
train.head()

first_row_left first_row_middle  ... bottom_row_right    is_win
0              x                x  ...                o  positive
1              x                x  ...                b  positive
2              x                x  ...                b  positive
3              x                x  ...                o  positive
4              x                x  ...                o  positive

[5 rows x 10 columns]

In [4]:
#Import .data file and rename the columns
test = pd.read_csv("ip2ttt_test.data", sep = ",")
test.columns = ["first_row_left", "first_row_middle", "first_row_right", 
                "center_row_left", "center_row_middle", "center_row_right", 
                "bottom_row_left", "bottom_row_middle", "bottom_row_right", "is_win"]
test.head()

first_row_left first_row_middle  ... bottom_row_right    is_win
0              x                x  ...                b  positive
1              x                x  ...                o  positive
2              x                x  ...                o  positive
3              x                x  ...                b  positive
4              x                x  ...                b  positive

[5 rows x 10 columns]

In [5]:
#Import .data file and rename the columns
valid = pd.read_csv("ip2ttt_valid.data", sep = ",")
valid.columns = ["first_row_left", "first_row_middle", "first_row_right", 
                 "center_row_left", "center_row_middle", "center_row_right", 
                 "bottom_row_left", "bottom_row_middle", "bottom_row_right", "is_win"]
valid.head()

first_row_left first_row_middle  ... bottom_row_right    is_win
0              x                x  ...                o  positive
1              x                x  ...                o  positive
2              x                x  ...                o  positive
3              x                x  ...                b  positive
4              x                x  ...                b  positive

[5 rows x 10 columns]

In [6]:
#Create dataframe and use get_dummies to change to 0s and 1s
df_train = pd.DataFrame(train)
train_getdummies = pd.get_dummies(df_train)
train_getdummies

first_row_left_b  first_row_left_o  ...  is_win_negative  is_win_positive
0                   0                 0  ...                0                1
1                   0                 0  ...                0                1
2                   0                 0  ...                0                1
3                   0                 0  ...                0                1
4                   0                 0  ...                0                1
..                ...               ...  ...              ...              ...
521                 0                 0  ...                1                0
522                 0                 1  ...                1                0
523                 0                 1  ...                1                0
524                 0                 1  ...                1                0
525                 0                 1  ...                1                0

[526 rows x 29 columns]

In [7]:
#Create dataframe and use get_dummies to change to 0s and 1s
df_test = pd.DataFrame(test)
test_getdummies = pd.get_dummies(df_test)
test_getdummies

first_row_left_b  first_row_left_o  ...  is_win_negative  is_win_positive
0                   0                 0  ...                0                1
1                   0                 0  ...                0                1
2                   0                 0  ...                0                1
3                   0                 0  ...                0                1
4                   0                 0  ...                0                1
..                ...               ...  ...              ...              ...
209                 1                 0  ...                1                0
210                 1                 0  ...                1                0
211                 0                 0  ...                1                0
212                 0                 0  ...                1                0
213                 0                 1  ...                1                0

[214 rows x 29 columns]

In [8]:
#Create dataframe and use get_dummies to change to 0s and 1s
df_valid = pd.DataFrame(valid)
valid_getdummies = pd.get_dummies(df_valid)
valid_getdummies

first_row_left_b  first_row_left_o  ...  is_win_negative  is_win_positive
0                   0                 0  ...                0                1
1                   0                 0  ...                0                1
2                   0                 0  ...                0                1
3                   0                 0  ...                0                1
4                   0                 0  ...                0                1
..                ...               ...  ...              ...              ...
210                 0                 0  ...                1                0
211                 0                 0  ...                1                0
212                 0                 0  ...                1                0
213                 0                 1  ...                1                0
214                 0                 1  ...                1                0

[215 rows x 29 columns]

In [9]:
#Merge dummy data with original data files
merged_train = pd.concat([df_train, train_getdummies], axis = "columns")
merged_train

first_row_left first_row_middle  ... is_win_negative is_win_positive
0                x                x  ...               0               1
1                x                x  ...               0               1
2                x                x  ...               0               1
3                x                x  ...               0               1
4                x                x  ...               0               1
..             ...              ...  ...             ...             ...
521              x                o  ...               1               0
522              o                x  ...               1               0
523              o                x  ...               1               0
524              o                x  ...               1               0
525              o                x  ...               1               0

[526 rows x 39 columns]

In [10]:
#Merge dummy data with original data files
merged_test = pd.concat([df_test, test_getdummies], axis = "columns")
merged_test

first_row_left first_row_middle  ... is_win_negative is_win_positive
0                x                x  ...               0               1
1                x                x  ...               0               1
2                x                x  ...               0               1
3                x                x  ...               0               1
4                x                x  ...               0               1
..             ...              ...  ...             ...             ...
209              b                b  ...               1               0
210              b                b  ...               1               0
211              x                x  ...               1               0
212              x                o  ...               1               0
213              o                x  ...               1               0

[214 rows x 39 columns]

In [11]:
#Merge dummy data with original data files
merged_valid = pd.concat([df_valid, valid_getdummies], axis = "columns")
merged_valid

first_row_left first_row_middle  ... is_win_negative is_win_positive
0                x                x  ...               0               1
1                x                x  ...               0               1
2                x                x  ...               0               1
3                x                x  ...               0               1
4                x                x  ...               0               1
..             ...              ...  ...             ...             ...
210              x                x  ...               1               0
211              x                x  ...               1               0
212              x                o  ...               1               0
213              o                x  ...               1               0
214              o                o  ...               1               0

[215 rows x 39 columns]

In [13]:
#For all the values within the 'is_win' column, assign 0 or 1 depending on positive or negative
train.loc[train['is_win'] == 'positive', 'is_win'] = 1
train.loc[train['is_win'] == 'negative', 'is_win'] = 0

train['is_win'].unique()

array([1, 0], dtype=object)

In [14]:
#For all the values within the 'is_win' column, assign 0 or 1 depending on positive or negative
test.loc[test['is_win'] == 'positive', 'is_win'] = 1
test.loc[test['is_win'] == 'negative', 'is_win'] = 0

test['is_win'].unique()

array([1, 0], dtype=object)

In [15]:
#For all the values within the 'is_win' column, assign 0 or 1 depending on positive or negative
valid.loc[valid['is_win'] == 'positive', 'is_win'] = 1
valid.loc[valid['is_win'] == 'negative', 'is_win'] = 0

valid['is_win'].unique()

array([1, 0], dtype=object)

In [16]:
#drop original data columns in .data files and keeps columns with dummy data
final_train = merged_train.drop(["first_row_left", "first_row_middle", "first_row_right", 
                                 "center_row_left", "center_row_middle", "center_row_right", 
                                 "bottom_row_left", "bottom_row_middle", "bottom_row_right", 
                                 "is_win_negative", "is_win_positive"], axis = "columns")
final_train

is_win  first_row_left_b  ...  bottom_row_right_o  bottom_row_right_x
0    positive                 0  ...                   1                   0
1    positive                 0  ...                   0                   0
2    positive                 0  ...                   0                   0
3    positive                 0  ...                   1                   0
4    positive                 0  ...                   1                   0
..        ...               ...  ...                 ...                 ...
521  negative                 0  ...                   1                   0
522  negative                 0  ...                   0                   1
523  negative                 0  ...                   0                   1
524  negative                 0  ...                   0                   1
525  negative                 0  ...                   0                   1

[526 rows x 28 columns]

In [17]:
#drop original data columns in .data files and keeps columns with dummy data
final_test = merged_test.drop(["first_row_left", "first_row_middle", "first_row_right", 
                               "center_row_left", "center_row_middle", "center_row_right", 
                               "bottom_row_left", "bottom_row_middle", "bottom_row_right", 
                               "is_win_negative", "is_win_positive"], axis = "columns")
final_test

is_win  first_row_left_b  ...  bottom_row_right_o  bottom_row_right_x
0    positive                 0  ...                   0                   0
1    positive                 0  ...                   1                   0
2    positive                 0  ...                   1                   0
3    positive                 0  ...                   0                   0
4    positive                 0  ...                   0                   0
..        ...               ...  ...                 ...                 ...
209  negative                 1  ...                   0                   1
210  negative                 1  ...                   0                   1
211  negative                 0  ...                   0                   1
212  negative                 0  ...                   1                   0
213  negative                 0  ...                   0                   1

[214 rows x 28 columns]

In [18]:
#drop original data columns in .data files and keeps columns with dummy data
final_valid = merged_valid.drop(["first_row_left", "first_row_middle", "first_row_right", 
                                 "center_row_left", "center_row_middle", "center_row_right", 
                                 "bottom_row_left", "bottom_row_middle", "bottom_row_right", 
                                 "is_win_negative", "is_win_positive"], axis = "columns")
final_valid

is_win  first_row_left_b  ...  bottom_row_right_o  bottom_row_right_x
0    positive                 0  ...                   1                   0
1    positive                 0  ...                   1                   0
2    positive                 0  ...                   1                   0
3    positive                 0  ...                   0                   0
4    positive                 0  ...                   0                   0
..        ...               ...  ...                 ...                 ...
210  negative                 0  ...                   1                   0
211  negative                 0  ...                   1                   0
212  negative                 0  ...                   1                   0
213  negative                 0  ...                   0                   1
214  negative                 0  ...                   0                   1

[215 rows x 28 columns]

In [19]:
#LabelEncoder is used to initilize y-values as 0s and 1s using the dataframe made before
le_train = LabelEncoder()
dfle_train = final_train
dfle_train.is_win = le_train.fit_transform(dfle_train.is_win)
y_train = dfle_train.is_win
y_train

0      1
1      1
2      1
3      1
4      1
      ..
521    0
522    0
523    0
524    0
525    0
Name: is_win, Length: 526, dtype: int64

In [20]:
#LabelEncoder is used to initilize y-values as 0s and 1s using the dataframe made before
le_test = LabelEncoder()
dfle_test = final_test
dfle_test.is_win = le_test.fit_transform(dfle_test.is_win)
y_test = dfle_test.is_win
y_test

0      1
1      1
2      1
3      1
4      1
      ..
209    0
210    0
211    0
212    0
213    0
Name: is_win, Length: 214, dtype: int64

In [21]:
#LabelEncoder is used to initilize y-values as 0s and 1s using the dataframe made before
le_valid = LabelEncoder()
dfle_valid = final_valid
dfle_valid.is_win = le_valid.fit_transform(dfle_valid.is_win)
y_valid = dfle_valid.is_win
y_valid

0      1
1      1
2      1
3      1
4      1
      ..
210    0
211    0
212    0
213    0
214    0
Name: is_win, Length: 215, dtype: int64

In [22]:
#Initilize the x-values 
x_train = dfle_train[["first_row_left_o", "first_row_left_x",
                    "first_row_middle_o", "first_row_middle_x",
                    "first_row_right_o", "first_row_right_x",
                    "center_row_left_o", "center_row_left_x",
                    "center_row_middle_o", "center_row_middle_x",
                    "center_row_right_o", "center_row_right_x", 
                    "bottom_row_left_o", "bottom_row_left_x",
                    "bottom_row_middle_o", "bottom_row_middle_x",
                    "bottom_row_right_o", "bottom_row_right_x"]].values
x_train


array([[0, 1, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1]], dtype=uint8)

In [23]:
#Initilize the x-values 
x_test = dfle_test[["first_row_left_o", "first_row_left_x",
                    "first_row_middle_o", "first_row_middle_x",
                    "first_row_right_o", "first_row_right_x",
                    "center_row_left_o", "center_row_left_x",
                    "center_row_middle_o", "center_row_middle_x",
                    "center_row_right_o", "center_row_right_x", 
                    "bottom_row_left_o", "bottom_row_left_x",
                    "bottom_row_middle_o", "bottom_row_middle_x",
                    "bottom_row_right_o", "bottom_row_right_x"]].values
x_test

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 1, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 1],
       [0, 1, 1, ..., 1, 1, 0],
       [1, 0, 0, ..., 0, 0, 1]], dtype=uint8)

In [24]:
#Initilize the x-values 
x_valid = dfle_valid[["first_row_left_o", "first_row_left_x",
                    "first_row_middle_o", "first_row_middle_x",
                    "first_row_right_o", "first_row_right_x",
                    "center_row_left_o", "center_row_left_x",
                    "center_row_middle_o", "center_row_middle_x",
                    "center_row_right_o", "center_row_right_x", 
                    "bottom_row_left_o", "bottom_row_left_x",
                    "bottom_row_middle_o", "bottom_row_middle_x",
                    "bottom_row_right_o", "bottom_row_right_x"]].values
x_valid

array([[0, 1, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 1, 0],
       ...,
       [0, 1, 1, ..., 1, 1, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 1, ..., 1, 0, 1]], dtype=uint8)

In [25]:
#Initizile the y-values
y_train = train['is_win'].astype('int')
y_train

0      1
1      1
2      1
3      1
4      1
      ..
521    0
522    0
523    0
524    0
525    0
Name: is_win, Length: 526, dtype: int64

In [26]:
#Initizile the y-values
y_test = test['is_win'].astype('int')
y_test

0      1
1      1
2      1
3      1
4      1
      ..
209    0
210    0
211    0
212    0
213    0
Name: is_win, Length: 214, dtype: int64

In [27]:
#Initizile the y-values
y_valid = valid['is_win'].astype('int')
y_valid

0      1
1      1
2      1
3      1
4      1
      ..
210    0
211    0
212    0
213    0
214    0
Name: is_win, Length: 215, dtype: int64

In [0]:
#Preprocessing Done. Values here are used later on.
#test-size: 0.3 for testing and 0.7 for training.
X_train, X_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.3, random_state=42)

In [29]:
#Logistic Regression with l2 and newton-cg
lr_newton = LogisticRegression(penalty= 'l2', solver='newton-cg')
lr_newton.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
#Logistic Regression with l2 and lbfgs
lr_lbfgs = LogisticRegression(penalty='l2', solver ='lbfgs')
lr_lbfgs.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
#Predict the values using X_train and X_test for newton-cg
pred_newton = lr_newton.predict(X_train)
print("\nLogistic Regression - Train accuracy (Eye Detection)", round(accuracy_score(y_train, pred_newton), 5))

pred_newton = lr_newton.predict(X_test)
print("\nLogistic Regression - Test accuracy (Eye Detection)", round(accuracy_score(y_test, pred_newton), 5))


Logistic Regression - Train accuracy (Eye Detection) 0.96467

Logistic Regression - Test accuracy (Eye Detection) 0.93038


In [32]:
#Predict the values using X_train and X_test for lbfgs
pred_lbfgs = lr_lbfgs.predict(X_train)
print("\nLogistic Regression - Train accuracy (Eye Detection)", round(accuracy_score(y_train, pred_lbfgs), 5))

pred_lbfgs = lr_lbfgs.predict(X_test)
print("\nLogistic Regression - Train accuracy (Eye Detection)", round(accuracy_score(y_test, pred_lbfgs), 5))


Logistic Regression - Train accuracy (Eye Detection) 0.96467

Logistic Regression - Train accuracy (Eye Detection) 0.93038


In [33]:
#Decision Tree Classifier
#Criterion is = 'entropy' for all. Keep changing min_samples_leaf values from 1-10
model_dtc = DecisionTreeClassifier(criterion = "entropy", min_samples_leaf = 1)
model_dtc.fit(X_train, y_train)
prediction_dtc = model_dtc.predict(X_test)
print('Decison Tree - Test accuracy: ', accuracy_score(prediction_dtc, y_test))

Decison Tree - Test accuracy:  0.9620253164556962


In [189]:
model_dtc = DecisionTreeClassifier(criterion = "entropy", min_samples_leaf = 2)
model_dtc.fit(X_train, y_train)
prediction_dtc = model_dtc.predict(X_test)
print('Decison Tree - Test accuracy: ', accuracy_score(prediction_dtc, y_test))

Decison Tree - Test accuracy:  0.9556962025316456


In [190]:
model_dtc = DecisionTreeClassifier(criterion = "entropy", min_samples_leaf = 3)
model_dtc.fit(X_train, y_train)
prediction_dtc = model_dtc.predict(X_test)
print('Decison Tree - Test accuracy: ', accuracy_score(prediction_dtc, y_test))

Decison Tree - Test accuracy:  0.8987341772151899


In [191]:
model_dtc = DecisionTreeClassifier(criterion = "entropy", min_samples_leaf = 4)
model_dtc.fit(X_train, y_train)
prediction_dtc = model_dtc.predict(X_test)
print('Decison Tree - Test accuracy: ', accuracy_score(prediction_dtc, y_test))

Decison Tree - Test accuracy:  0.8924050632911392


In [192]:
model_dtc = DecisionTreeClassifier(criterion = "entropy", min_samples_leaf = 5)
model_dtc.fit(X_train, y_train)
prediction_dtc = model_dtc.predict(X_test)
print('Decison Tree - Test accuracy: ', accuracy_score(prediction_dtc, y_test))

Decison Tree - Test accuracy:  0.8860759493670886


In [193]:
model_dtc = DecisionTreeClassifier(criterion = "entropy", min_samples_leaf = 6)
model_dtc.fit(X_train, y_train)
prediction_dtc = model_dtc.predict(X_test)
print('Decison Tree - Test accuracy: ', accuracy_score(prediction_dtc, y_test))

Decison Tree - Test accuracy:  0.8544303797468354


In [194]:
model_dtc = DecisionTreeClassifier(criterion = "entropy", min_samples_leaf = 7)
model_dtc.fit(X_train, y_train)
prediction_dtc = model_dtc.predict(X_test)
print('Decison Tree - Test accuracy: ', accuracy_score(prediction_dtc, y_test))

Decison Tree - Test accuracy:  0.8607594936708861


In [195]:
model_dtc = DecisionTreeClassifier(criterion = "entropy", min_samples_leaf = 8)
model_dtc.fit(X_train, y_train)
prediction_dtc = model_dtc.predict(X_test)
print('Decison Tree - Test accuracy: ', accuracy_score(prediction_dtc, y_test))

Decison Tree - Test accuracy:  0.8291139240506329


In [196]:
model_dtc = DecisionTreeClassifier(criterion = "entropy", min_samples_leaf = 9)
model_dtc.fit(X_train, y_train)
prediction_dtc = model_dtc.predict(X_test)
print('Decison Tree - Test accuracy: ', accuracy_score(prediction_dtc, y_test))

Decison Tree - Test accuracy:  0.8291139240506329


In [197]:
model_dtc = DecisionTreeClassifier(criterion = "entropy", min_samples_leaf = 10)
model_dtc.fit(X_train, y_train)
prediction_dtc = model_dtc.predict(X_test)
print('Decison Tree - Test accuracy: ', accuracy_score(prediction_dtc, y_test))

Decison Tree - Test accuracy:  0.8037974683544303


In [199]:
#KNeighborsClassifier
#Change the number of n_neighbors --> 1, 3, 5, 7, 9
clf3 = KNeighborsClassifier(n_neighbors=1)
clf3.fit(X_train, y_train) #training first
k_score = clf3.score(X_test, y_test) #use testing variables
k_score

0.9936708860759493

In [200]:
k_score_valid = clf3.score(x_valid, y_valid) #use validation variables
k_score_valid

1.0

In [202]:
clf3 = KNeighborsClassifier(n_neighbors=3)
clf3.fit(X_train, y_train) #training first 
k_score = clf3.score(X_test, y_test) #use testing variables
k_score

0.9746835443037974

In [203]:
k_score_valid = clf3.score(x_valid, y_valid) #use validation variables
k_score_valid

0.958139534883721

In [204]:
clf3 = KNeighborsClassifier(n_neighbors=5)
clf3.fit(X_train, y_train) #training first
k_score = clf3.score(X_test, y_test) #use testing variables
k_score

0.9556962025316456

In [205]:
k_score_valid = clf3.score(x_valid, y_valid) #use validation variables
k_score_valid

0.9069767441860465

In [206]:
clf3 = KNeighborsClassifier(n_neighbors=7)
clf3.fit(X_train, y_train) #training first
k_score = clf3.score(X_test, y_test) #use testing variables
k_score

0.9240506329113924

In [207]:
k_score_valid = clf3.score(x_valid, y_valid) #use validation variables
k_score_valid

0.8465116279069768

In [208]:
clf3 = KNeighborsClassifier(n_neighbors=9)
clf3.fit(X_train, y_train) #training first
k_score = clf3.score(X_test, y_test) #use testing variables
k_score

0.8860759493670886

In [209]:
k_score_valid = clf3.score(x_valid, y_valid) #use validation variables
k_score_valid

0.8418604651162791

In [40]:
#RandomForest Classifier 
#Change max_depth and min_samples_leaf values
rf = RandomForestClassifier(max_depth=3, min_samples_leaf=5)
rf.fit(X_train, y_train) #training first
rf_predict = rf.predict(X_test) #predict using X_test variable

#AUC - Area Under the Curve
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, rf_predict) #use prediction output and y_test variable
roc_auc = auc(false_positive_rate, true_positive_rate)
roc_auc

0.6768207282913166

In [0]:
rf_predict = rf.predict(x_valid) #use validation variable 
rf_predict

In [45]:
#RandomForest Classifier 
#Change max_depth and min_samples_leaf values
rf = RandomForestClassifier(max_depth=5, min_samples_leaf=10)
rf.fit(X_train, y_train)
rf_predict = rf.predict(X_test)

#AUC - Area Under the Curve
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, rf_predict) #use prediction output and y_test variable
roc_auc = auc(false_positive_rate, true_positive_rate)
roc_auc

0.7036064425770308

In [0]:
rf_predict = rf.predict(x_valid) #use validation variable 
rf_predict

In [47]:
#RandomForest Classifier 
#Change max_depth and min_samples_leaf values
rf = RandomForestClassifier(max_depth=3, min_samples_leaf=10)
rf.fit(X_train, y_train)
rf_predict = rf.predict(X_test)

#AUC - Area Under the Curve
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, rf_predict) #use prediction output and y_test variable
roc_auc = auc(false_positive_rate, true_positive_rate)
roc_auc

0.636204481792717

In [0]:
rf_predict = rf.predict(x_valid) #use validation variable 
rf_predict

In [48]:
#RandomForest Classifier 
#Change max_depth and min_samples_leaf values
rf = RandomForestClassifier(max_depth=5, min_samples_leaf=10)
rf.fit(X_train, y_train)
rf_predict = rf.predict(X_test)

#AUC - Area Under the Curve
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, rf_predict) #use prediction output and y_test variable
roc_auc = auc(false_positive_rate, true_positive_rate)
roc_auc

0.6889005602240896

In [49]:
rf_predict = rf.predict(x_valid) #use validation variable 
rf_predict

array([1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1])